controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

ajax_city_list:
    path: /ajax/city-list
    controller: App\Controller\Ajax\CityListController::cityListAction
